### ISSUE TITLE
Attribute `dialect_list` returns `TypeError`

### ISSUE THREAD

**Issue by agonzalezd** [MiniXC/phones#10]
I know it's not documented in the [API reference](https://cdminix.me/phones/reference/#phones.PhoneCollection), but attribute/method/property `PhoneCollection.dialect_list` returns `TypeError`:

```python3

>>> from phones import PhoneCollection
>>> pc = PhoneCollection(load_dialects=True)
>>> pc.langs("eus").dialect_list
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/python3.8/site-packages/phones/__init__.py", line 135, in dialect_list
    return list(sorted(self.data[self.source.dialect_column].unique()))
TypeError: '<' not supported between instances of 'float' and 'str'
```

It marks an error [here](https://github.com/MiniXC/phones/blob/main/src/phones/__init__.py#L135)

I am using version 0.0.4

It might be still on testing phase since it is not documented, but in case you still haven't notice this bug.

Thanks in advance!

**Comment by MiniXC** [comment]
Turns out this was a problem with NaN appearing in the data, will be fixed in 0.0.5
